#@remotejdk11_linux
local_repository(
    name = "remotejdk11_linux",
    path = "src/manual_3/remotejdk11_linux",
)


#go_sdk
local_repository(
    name = "go_sdk",
    path = "src/manual_3/go_sdk",
)

# zlib
local_repository(
    name = "zlib",
    path = "src/manual_3/zlib",
)

#@io_bazel_rules_go
local_repository(
    name = "io_bazel_rules_go",
    path = "src/manual_3/io_bazel_rules_go",
)
#@build_bazel_rules_apple
local_repository(
    name = "build_bazel_rules_apple",
    path = "src/manual_3/build_bazel_rules_apple",
)
#envoy_api
local_repository(
    name = "envoy_api",
    path = "src/manual_3/envoy_api",
)



#@boringssl
local_repository(
    name = "boringssl",
    path = "src/manual_3/boringssl",
)
#@com_github_cares_cares
local_repository(
    name = "com_github_cares_cares",
    path = "src/manual_3/com_github_cares_cares",
)

# Google Protocol Buffers.
local_repository(
    name = "com_google_protobuf",
    path = "src/manual_3/com_google_protobuf",
)

local_repository(
    name = "rules_proto",
    path = "src/manual_3/rules_proto",
)
load("@rules_proto//proto:repositories.bzl", "rules_proto_dependencies", "rules_proto_toolchains")
rules_proto_dependencies()
rules_proto_toolchains()


# Google Abseil C++ Library
# Example Useage: #include "absl/string"
local_repository(
    name = "com_google_absl",
    path = "src/manual_3/com_google_absl",
)

# GoogleTest
# Example Useage: #include "gtest/gtest.h"
local_repository(
    name = "com_google_test",
    path = "src/manual_3/com_google_test",
)

# gRPC
local_repository(
    name = "com_github_grpc_grpc",
    path = "src/manual_3/com_github_grpc_grpc",
)



load("@com_github_grpc_grpc//bazel:grpc_deps.bzl", "grpc_deps")

grpc_deps()

load("@com_github_grpc_grpc//bazel:grpc_extra_deps.bzl", "grpc_extra_deps")

grpc_extra_deps()

# LevelDb
# Example dependency: "@com_google_leveldb//:leveldb"
local_repository(
    name = "com_google_leveldb",
    path = "src/manual_3/com_google_leveldb",
)

# Parallel Hashmap
# https://greg7mdp.github.io/parallel-hashmap/
local_repository(
    name = "parallel_hashmap",
    path = "src/manual_3/parallel_hashmap",
)

# Google glog C++ logging library
# Note: Don't use directly in your code,
#       see examples/system_logger_main.cc for how to log.
# Example Usage: #include "glog/logging.h"
# Example dependency: "@com_google_glog//:glog"
local_repository(
    name = "com_google_glog",
    path = "src/manual_3/com_google_glog",
)
# YAML Parser
# https://github.com/jbeder/yaml-cpp
local_repository(
    name = "yaml_cpp",
    path = "src/manual_3/yaml_cpp",
)

# Google Benchmark library
local_repository(
    name = "com_google_benchmark",
    path = "src/manual_3/com_google_benchmark",
)





